### ISSUE TITLE
Fixed Ledger typo

### ISSUE THREAD

**Issue by TomBers** [ash-project/ash_double_entry#1]
**Describe the bug**

When following this tutorial - https://hexdocs.pm/ash_double_entry/get-started-with-double-entry.html (documentation/tutorials/get-started-with-double-entry.md) there are the following:

```
defmodule YourApp.Leger.Account do
```

and 

```
defmodule YourApp.Transfer do
```

For people new to Ash, this might cause some minor issues. (BTW great work on Ash, it is a very interesting framework)

**Comment by zachdaniel** [comment]
Thanks! Fixed
